/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_evilbinary_rs_Rs */

#ifndef _Included_org_evilbinary_rs_Rs
#define _Included_org_evilbinary_rs_Rs
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_evilbinary_rs_Rs
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_evilbinary_rs_Rs_init
  (JNIEnv *, jobject);

/*
 * Class:     org_evilbinary_rs_Rs
 * Method:    eval
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_evilbinary_rs_Rs_eval
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_evilbinary_rs_Rs
 * Method:    exit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_evilbinary_rs_Rs_exit
  (JNIEnv *, jobject);


#ifdef __cplusplus
}
#endif
#endif
